---
layout: cv
title: Jayden Chen's CV
---
# Jayden Chen
Rexburg, Idaho 83440  
(435) 314-5523  
<a href="mailto:haij0428@gmail.com">haij0428@gmail.com</a>

## Education

`Spring 2024`  
__Snow College__  
- General Education  
- GPA: 3.50

`Present`  
__Brigham Young University - Idaho (BYUI)__  
- Computer Science  
- GPA: 4.0

## Experience

`May 2020 - Dec 2020`  
__Zhuhai Chengtai Automobile Sales Service Co., Ltd__  
- Demonstrated in-depth knowledge of vehicle features and benefits to customers.  
- Developed and presented customized financial solutions.  
- Fostered customer loyalty through excellent service.  
- Delivered personalized customer experiences.

`Dec 2020 - Jun 2021`  
__Chehaotian Maintenance Center__  
- Diagnosed and troubleshot vehicle issues.  
- Repaired and maintained vehicles to high standards.  
- Gained proficiency with automotive tools and equipment.

`Aug 2021 - Nov 2021`  
__Ke Holdings Inc.__  
- Presented value propositions of real estate offerings.  
- Built customer relationships and loyalty.  
- Analyzed client needs and suggested financial solutions.  
- Led daily operations and team coordination.

`May 2022 – Aug 2024`  
__Snow College Campus Services__  
- Building cleaning and maintenance services.

## Service & Volunteer

__Urban Service Volunteers__  
- Promoted traffic civilization in coordination with law enforcement.  
- Prevented violations and maintained order.

__BYUI__  
- Volunteer at Chinese conversation lab.

## Leadership and Activities

__Construction Site Assistant__  
- Guided billboard installation.  
- Led circuit installation projects.

## Skills

- **Computer**: Python, Microsoft Office, computer maintenance  
- **Languages**: English, Mandarin, Cantonese  
- **Problem-Solving**: Strong analytical skills, adaptability, composure under pressure  
- **Teamwork & Leadership**: Idea integration, communication, team coordination